name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync
        run: |
          curl -X POST "https://voila-api.mmopro.in/sync-app" \
            -H "Content-Type: application/json" \
            -d "{\"app\": \"jan27localapptest-1769493635009\", \"repo\": \"https://github.com/BharatSharma34/jan27localapptest-1769493635009.git\", \"github_token\": \"${{ secrets.PRIVATE_GITHUB_TOKEN }}\"}"